spring:
  application:
    name: sudoku-app-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sudokudb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #OAuth2 / OIDC issuer URI
          # See README for vendor-specific examples
          issuer-uri: ${ISSUER_URI}

  flyway:
    enabled: true
    # PostgreSQL固有の型（ENUM等）を扱うため、必要に応じて設定
    baseline-on-migrate: true