-- 1. Enum型の定義 (PostgreSQL)
CREATE TYPE log_status AS ENUM ('FAILED', 'HINT_USED', 'SOLVED');
CREATE TYPE user_board_status AS ENUM ('IN_PROGRESS', 'COMPLETED');

-- 2. テーブル作成
CREATE TABLE users (
    uid VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE board (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cell (
    board_id BIGINT NOT NULL,
    row_idx INTEGER NOT NULL CHECK (row_idx >= 0 AND row_idx <= 8),
    col_idx INTEGER NOT NULL CHECK (col_idx >= 0 AND col_idx <= 8),
    initial_value INTEGER CHECK (initial_value >= 1 AND initial_value <= 9),
    correct_value INTEGER CHECK (correct_value >= 1 AND correct_value <= 9),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (board_id, row_idx, col_idx),
    CONSTRAINT fk_cell_board FOREIGN KEY (board_id) REFERENCES board(id)
);

CREATE TABLE user_board (
    board_id BIGINT NOT NULL,
    uid VARCHAR(255) NOT NULL,
    status user_board_status NOT NULL,
    last_hint_used TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (board_id, uid), -- Hibernateの出力に合わせて (board_id, uid) の順
    CONSTRAINT fk_user_board_board FOREIGN KEY (board_id) REFERENCES board(id),
    CONSTRAINT fk_user_board_user FOREIGN KEY (uid) REFERENCES users(uid)
);

CREATE TABLE log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    board_id BIGINT,
    uid VARCHAR(255),
    row_idx INTEGER,
    col_idx INTEGER,
    input_number INTEGER,
    status log_status NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    -- UserBoardへの外部キー (親のPK順序と一致させる)
    CONSTRAINT fk_log_user_board FOREIGN KEY (board_id, uid) REFERENCES user_board(board_id, uid) ON DELETE CASCADE,
    -- Cellへの外部キー
    CONSTRAINT fk_log_cell FOREIGN KEY (board_id, row_idx, col_idx) REFERENCES cell(board_id, row_idx, col_idx)
);